[#bridge]
= 桥接模式

== 定义

根据 GoF 的著名著作 {bk_dp}，桥接模式的定义如下：

[quote,{bkn_dp}]
____
桥接模式（Bridge）::
将抽象部分与它的实现部分分离，使它们都可以独立地变化。
____

== 类图

plantuml::assets/puml/bridge.puml[{puml_attr}]

什么叫抽象与它的实现分离，这并不是说，让抽象类与其派生类分离，因为这没有任何意义。实现指的是抽象类和它的派生类用来实现自己的对象[DPE]。

桥接模式的核心意图就是把这些实现独立出来，让它们各自地变化。这就使得每种实现的变化不会影响其他实现，从而达到应对变化的目的。

Implementor类

ConcreteImplementorA和ConcreteImplementorB等派生类

Abstraction类

RefinedAbstraction类

桥接模式所说的‘将抽象部分与它的实现部分分离’，还是不好理解，我的理解就是实现系统可能有多角度分类，每一种分类都有可能变化，那么就把这种多角度分离出来让它们独立变化，减少它们之间的耦合。

在发现我们需要多角度去分类实现对象，而只用继承会造成大量的类增加，不能满足开放-封闭原则时，就应该要考虑用桥接模式了。

只要真正深入地理解了设计原则，很多设计模式其实就是原则的应用而已，或许在不知不觉中就在使用设计模式了。

[{java_source_attr}]
.bridge/Abstraction.java 类
[#src-bridge-abstraction]
----
include::{source_dir}/bridge/Abstraction.java[]
----



[{java_source_attr}]
.bridge/ConcreteImplementorA.java 类
[#src-bridge-concreteimplementora]
----
include::{source_dir}/bridge/ConcreteImplementorA.java[]
----



[{java_source_attr}]
.bridge/ConcreteImplementorB.java 类
[#src-bridge-concreteimplementorb]
----
include::{source_dir}/bridge/ConcreteImplementorB.java[]
----



[{java_source_attr}]
.bridge/Implementor.java 类
[#src-bridge-implementor]
----
include::{source_dir}/bridge/Implementor.java[]
----



[{java_source_attr}]
.bridge/RefinedAbstraction.java 类
[#src-bridge-refinedabstraction]
----
include::{source_dir}/bridge/RefinedAbstraction.java[]
----



[{java_source_attr}]
.bridge/Client.java 类
[#src-bridge-client]
----
include::{source_dir}/bridge/Client.java[]
----

== 常见示例

. JDBC
. AWT
