[#factory-method]
= 工厂方法模式

== 定义

根据 GoF 的著名著作 {bk_dp}，工厂方法模式的定义如下：

[quote,{bkn_dp}]
____
工厂方法模式（Factory Method）::
定义一个用于创建对象的接口，让子类决定实例化哪一个类。工厂方法使一个类的实例化延迟到其子类。
____

== 类图

plantuml::assets/puml/factory-method.puml[{puml_attr}]

简单工厂模式的最大优点在于工厂类中包含了必要的逻辑判断，根据客户端的选择条件动态实例化相关的类，对于客户端来说，去除了与具体产品的依赖。

既然这个工厂类与分支耦合，那么我就对它下手，根据依赖倒转原则，我们把工厂类抽象出一个接口，这个接口只有一个方法，就是创建抽象产品的工厂方法。然后，所有的要生产具体类的工厂，就去实现这个接口，这样，一个简单工厂模式的工厂类，变成了一个工厂抽象接口和多个具体生成对象的工厂，

工厂方法模式实现时，客户端需要决定实例化哪一个工厂来实现运算类，选择判断的问题还是存在的，也就是说，工厂方法把简单工厂的内部逻辑判断移到了客户端代码来进行。你想要加功能，本来是改工厂类的，而现在是修改客户端！

工厂方法克服了简单工厂违背开放-封闭原则的缺点，又保持了封装对象创建过程的优点。

它们都是集中封装了对象的创建，使得要更换对象时，不需要做大的改动就可实现，降低了客户程序与产品对象的耦合。工厂方法模式是简单工厂模式的进一步抽象和推广。由于使用了多态性，工厂方法模式保持了简单工厂模式的优点，而且克服了它的缺点。但缺点是由于每加一个产品，就需要加一个产品工厂的类，增加了额外的开发量。

利用‘反射’可以解决避免分支判断的问题。

[{java_source_attr}]
.factorymethod/ConcreteFactory.java 类
[#src-factorymethod-concretefactory]
----
include::{source_dir}/factorymethod/ConcreteFactory.java[]
----



[{java_source_attr}]
.factorymethod/ConcreteProduct.java 类
[#src-factorymethod-concreteproduct]
----
include::{source_dir}/factorymethod/ConcreteProduct.java[]
----



[{java_source_attr}]
.factorymethod/Factory.java 类
[#src-factorymethod-factory]
----
include::{source_dir}/factorymethod/Factory.java[]
----



[{java_source_attr}]
.factorymethod/Product.java 类
[#src-factorymethod-product]
----
include::{source_dir}/factorymethod/Product.java[]
----



[{java_source_attr}]
.factorymethod/Client.java 类
[#src-factorymethod-client]
----
include::{source_dir}/factorymethod/Client.java[]
----
