[#flyweight]
= 享元模式

plantuml::assets/puml/flyweight.puml[{puml_attr}]

Flyweight类，它是所有具体享元类的超类或接口，通过这个接口，Flyweight可以接受并作用于外部状态。

ConcreteFlyweight是继承Flyweight超类或实现Flyweight接口，并为内部状态增加存储空间。

UnsharedConcreteFlyweight是指那些不需要共享的Flyweight子类。因为Flyweight接口共享成为可能，但它并不强制共享。

FlyweightFactory，是一个享元工厂，用来创建并管理Flyweight对象。它主要是用来确保合理地共享Flyweight，当用户请求一个Flyweight时，FlyweightFactory对象提供一个已创建的实例或者创建一个（如果不存在的话）。

尽管我们大部分时间都需要共享对象来降低内存的损耗，但个别时候也有可能不需要共享的，那么此时的UnsharedConcreteFlyweight子类就有存在的必要了，它可以解决那些不需要共享对象的问题。

在享元对象内部并且不会随环境改变而改变的共享部分，可以称为是享元对象的内部状态，而随环境改变而改变的、不可以共享的状态就是外部状态了。事实上，享元模式可以避免大量非常相似类的开销。在程序设计中，有时需要生成大量细粒度的类实例来表示数据。如果能发现这些实例除了几个参数外基本上都是相同的，有时就能够受大幅度地减少需要实例化的类的数量。如果能把那些参数移到类实例的外面，在方法调用时将它们传递进来，就可以通过共享大幅度地减少单个实例的数目。也就是说，享元模式Flyweight执行时所需的状态是有内部的也可能有外部的，内部状态存储于ConcreteFlyweight对象之中，而外部对象则应该考虑由客户端对象存储或计算，当调用Flyweight对象的操作时，将该状态传递给它。

如果一个应用程序使用了大量的对象，而大量的这些对象造成了很大的存储开销时就应该考虑使用；还有就是对象的大多数状态可以外部状态，如果删除对象的外部状态，那么可以用相对较少的共享对象取代很多组对象，此时可以考虑使用享元模式。

用了享元模式，所以有了共享对象，实例总数就大大减少了，如果共享的对象越多，存储节约也就越多，节约量随着共享状态的增多而增大。

实际上在.NET中，字符串string就是运用了Flyweight模式。举个例子吧。Object.ReferenceEquals（object objA,object objB）方法是用来确定objA与objB是否是相同的实例，返回值为bool值

享元模式更多的时候是一种底层的设计模式

在某些情况下，对象的数量可能会太多，从而导致了运行时的资源与性能损耗。那么我们如何去避免大量细粒度的对象，同时又不影响客户程序，是一个值得去思考的问题，享元模式，可以运用共享技术有效地支持大量细粒度的对象。

使用享元模式需要维护一个记录了系统已有的所有享元的列表，而这本身需要耗费资源，另外享元模式使得系统更加复杂。为了使对象可以共享，需要将一些状态外部化，这使得程序的逻辑复杂化。因此，应当在有足够多的对象实例可供共享时才值得使用享元模式。

[{java_source_attr}]
.flyweight/Client.java 类
[#src-flyweight-client]
----
include::{source_dir}/flyweight/Client.java[]
----



[{java_source_attr}]
.flyweight/ConcreteFlyWeight.java 类
[#src-flyweight-concreteflyweight]
----
include::{source_dir}/flyweight/ConcreteFlyWeight.java[]
----



[{java_source_attr}]
.flyweight/FlyWeight.java 类
[#src-flyweight-flyweight]
----
include::{source_dir}/flyweight/FlyWeight.java[]
----



[{java_source_attr}]
.flyweight/FlyweightFactory.java 类
[#src-flyweight-flyweightfactory]
----
include::{source_dir}/flyweight/FlyweightFactory.java[]
----



[{java_source_attr}]
.flyweight/UnsharedConcreteFlyWeight.java 类
[#src-flyweight-unsharedconcreteflyweight]
----
include::{source_dir}/flyweight/UnsharedConcreteFlyWeight.java[]
----


