[#iterator]
= 迭代器模式

== 定义

根据 GoF 的著名著作 {bk_dp}，迭代器模式的定义如下：

[quote,{bkn_dp}]
____
迭代器模式（Iterator）::
提供一种方法顺序访问一个聚合对象中各个元素，而又不暴露该对象的内部表示。
____

== 类图

plantuml::assets/puml/iterator.puml[{puml_attr}]

迭代器模式
注: 结合 Java 中 Iterator 和 Iteratable ，具体分析一下迭代器在 Java 中的实现。另外，重点看看内迭代器和外迭代器之间的不同实现。

迭代器模式。

当你需要访问一个聚集对象，而且不管这些对象是什么都需要遍历的时候，你就应该考虑用迭代器模式。

你需要对聚集有多种方式遍历时，可以考虑用迭代器模式。

为遍历不同的聚集结构提供如开始、下一个、是否结束、当前哪一项等统一的接口。

像IEnumerable接口也是为迭代器模式而准备的。不管如何，学习一下GoF的迭代器模式的基本结构，还是很有学习价值的。研究历史是为了更好地迎接未来。

Iterator迭代器抽象类

Aggregate聚集抽象类

ConcreteIterator具体迭代器类，继承Iterator

ConcreteAggregate具体聚集类继承Aggregate

当你需要对聚集有多种方式遍历时，可以考虑用迭代器模式

尽管我们不需要显式的引用迭代器，但系统本身还是通过迭代器来实现遍历的。总地来说，迭代器（Iterator）模式就是分离了集合对象的遍历行为，抽象出一个迭代器类来负责，这样既可以做到不暴露集合的内部结构，又可让外部代码透明地访问集合内部的数据。

[{java_source_attr}]
.iterator/Aggregate.java 类
[#src-iterator-aggregate]
----
include::{source_dir}/iterator/Aggregate.java[]
----



[{java_source_attr}]
.iterator/Client.java 类
[#src-iterator-client]
----
include::{source_dir}/iterator/Client.java[]
----



[{java_source_attr}]
.iterator/ConcreteAggregate.java 类
[#src-iterator-concreteaggregate]
----
include::{source_dir}/iterator/ConcreteAggregate.java[]
----



[{java_source_attr}]
.iterator/ConcreteIterator.java 类
[#src-iterator-concreteiterator]
----
include::{source_dir}/iterator/ConcreteIterator.java[]
----



[{java_source_attr}]
.iterator/Iterator.java 类
[#src-iterator-iterator]
----
include::{source_dir}/iterator/Iterator.java[]
----

== 常见示例

. `java.util.Iterator`
