[#memento]
= 备忘录模式

plantuml::assets/puml/memento.puml[{puml_attr}]

代码无错未必优。

Originator（发起人）：负责创建一个备忘录Memento，用以记录当前时刻它的内部状态，并可使用备忘录恢复内部状态。Originator可根据需要决定Memento存储Originator的哪些内部状态。

Memento（备忘录）：负责存储Originator对象的内部状态，并可防止Originator以外的其他对象访问备忘录Memento。备忘录有两个接口，Caretaker只能看到备忘录的窄接口，它只能将备忘录传递给其他对象。Originator能够看到一个宽接口，允许它访问返回到先前状态所需的所有数据。

Caretaker（管理者）：负责保存好备忘录Memento，不能对备忘录的内容进行操作或检查。 “

要保存的细节给封装在了Memento中了，哪一天要更改保存的细节也不用影响客户端了。

Memento模式比较适用于功能比较复杂的，但需要维护或记录属性历史的类，或者需要保存的属性只是众多属性中的一小部分时，Originator可以根据保存的Memento信息还原到前一状态。

如果在某个系统中使用命令模式时，需要实现命令的撤销功能，那么命令模式可以使用备忘录模式来存储可撤销操作的状态[DP]

有时一些对象的内部信息必须保存在对象以外的地方，但是必须要由对象自己读取，这时，使用备忘录可以把复杂的对象内部信息对其他的对象屏蔽起来[DP]，从而可以恰当地保持封装的边界。

最大的作用还是在当角色的状态改变的时候，有可能这个状态无效，这时候就可以使用暂时存储起来的备忘录将状态复原[DP]

整体与部分可以被一致对待的问题。

[{java_source_attr}]
.memento/Caretaker.java 类
[#src-memento-caretaker]
----
include::{source_dir}/memento/Caretaker.java[]
----



[{java_source_attr}]
.memento/Memento.java 类
[#src-memento-memento]
----
include::{source_dir}/memento/Memento.java[]
----



[{java_source_attr}]
.memento/Originator.java 类
[#src-memento-originator]
----
include::{source_dir}/memento/Originator.java[]
----



[{java_source_attr}]
.memento/Client.java 类
[#src-memento-client]
----
include::{source_dir}/memento/Client.java[]
----
