[#prototype]
= 原型模式

== 定义

根据 GoF 的著名著作 {bk_dp}，原型模式的定义如下：

[quote,{bkn_dp}]
____
原型模式（Prototype）::
用原型实例指定创建对象的种类，并且通过拷贝这些原型创建新的对象。
____

== 类图

plantuml::assets/puml/prototype.puml[{puml_attr}]

原型模式其实就是从一个对象再创建另外一个可定制的对象，而且不需知道任何创建的细节。

.NET在System命名空间中提供了ICloneable接口，其中就是唯一的一个方法Clone()，这样你就只需要实现这个接口就可以完成原型模式了。

一般在初始化的信息不发生变化的情况下，克隆是最好的办法。这既隐藏了对象创建的细节，又对性能是大大的提高，

不用重新初始化对象，而是动态地获得对象运行时的状态。

MemberwiseClone()方法是这样，如果字段是值类型的，则对该字段执行逐位复制，如果字段是引用类型，则复制引用但不复制引用的对象；因此，原始对象及其复本引用同一对象。

‘浅复制’，被复制对象的所有变量都含有与原来的对象相同的值，而所有的对其他对象的引用都仍然指向原来的对象。

把要复制的对象所引用的对象都复制一遍。

叫这种方式为‘深复制’，深复制把引用对象的变量指向复制过的新对象，而不是原有的被引用的对象。

深复制要深入到多少层，需要事先就考虑好，而且要当心出现循环引用的问题，需要小心处理，这里比较复杂，可以慢慢研究。

[{java_source_attr}]
.prototype/Client.java 类
[#src-prototype-client]
----
include::{source_dir}/prototype/Client.java[]
----



[{java_source_attr}]
.prototype/ConcretePrototype1.java 类
[#src-prototype-concreteprototype1]
----
include::{source_dir}/prototype/ConcretePrototype1.java[]
----



[{java_source_attr}]
.prototype/ConcretePrototype2.java 类
[#src-prototype-concreteprototype2]
----
include::{source_dir}/prototype/ConcretePrototype2.java[]
----



[{java_source_attr}]
.prototype/Prototype.java 类
[#src-prototype-prototype]
----
include::{source_dir}/prototype/Prototype.java[]
----


== 常见示例

. `java.lang.Object.clone()`
. `java.lang.Cloneable`
