[#state]
= 状态模式

== 定义

根据 GoF 的著名著作 {bk_dp}，状态模式的定义如下：

[quote,{bkn_dp}]
____
状态模式（State）::
当一个对象的内在状态改变时允许改变其行为，这个对象看起来像是改变了其类。
____

== 类图

plantuml::assets/puml/state.puml[{puml_attr}]


MartinFowler曾在《重构》中写过一个很重要的代码坏味道，叫做‘Long Method’，方法如果过长其实极有可能是有坏味道了。

面向对象设计其实就是希望做到代码的责任分解。

状态模式主要解决的是当控制一个对象状态转换的条件表达式过于复杂时的情况。把状态的判断逻辑转移到表示不同状态的一系列类当中，可以把复杂的判断逻辑简化。

State类，抽象状态类，定义一个接口以封装与Context的一个特定状态相关的行为。

ConcreteState类，具体状态，每一个子类实现一个与Context的一个状态相关的行为。

Context类，维护一个ConcreteState子类的实例，这个实例定义当前的状态。

状态模式的好处是将与特定状态相关的行为局部化，并且将不同状态的行为分割开来[DP]。

将特定的状态相关的行为都放入一个对象中，由于所有与状态相关的代码都存在于某个ConcreteState中，所以通过定义新的子类可以很容易地增加新的状态和转换[DP]。

这样做的目的就是为了消除庞大的条件分支语句，大的分支判断会使得它们难以修改和扩展，就像我们最早说的刻版印刷一样，任何改动和变化都是致命的。状态模式通过把各种状态转移逻辑分布到State的子类之间，来减少相互间的依赖，好比把整个版面改成了一个又一个的活字，此时就容易维护和扩展了。

当一个对象的行为取决于它的状态，并且它必须在运行时刻根据状态改变它的行为时，就可以考虑使用状态模式了。

[{java_source_attr}]
.state/ConcreteStateA.java 类
[#src-state-concretestatea]
----
include::{source_dir}/state/ConcreteStateA.java[]
----



[{java_source_attr}]
.state/ConcreteStateB.java 类
[#src-state-concretestateb]
----
include::{source_dir}/state/ConcreteStateB.java[]
----



[{java_source_attr}]
.state/ConcreteStateC.java 类
[#src-state-concretestatec]
----
include::{source_dir}/state/ConcreteStateC.java[]
----



[{java_source_attr}]
.state/Context.java 类
[#src-state-context]
----
include::{source_dir}/state/Context.java[]
----



[{java_source_attr}]
.state/State.java 类
[#src-state-state]
----
include::{source_dir}/state/State.java[]
----



[{java_source_attr}]
.state/Client.java 类
[#src-state-client]
----
include::{source_dir}/state/Client.java[]
----

== 常见示例

. `java.util.Iterator`