[[abstract-factory]]
== 抽象工厂模式

plantuml::./puml/abstract-factory.puml[target={puml_target_dir}/abstract-factory,{puml_attr}]

菜鸟程序员碰到问题，只会用时间来摆平

工厂方法模式是定义一个用于创建对象的接口，让子类决定实例化哪一个类。

AbstractProductA和AbstractProductB是两个抽象产品，之所以为抽象，是因为它们都有可能有两种不同的实现，就刚才的例子来说就是User和Department，而ProductA1、ProductA2和ProductB1、ProductB2就是对两个抽象产品的具体分类的实现

IFactory是一个抽象工厂接口，它里面应该包含所有的产品创建的抽象方法。而ConcreteFactory1和ConcreteFactory2就是具体的工厂了。

通常是在运行时刻再创建一个ConcreteFactory类的实例，这个具体的工厂再创建具有特定实现的产品对象，也就是说，为创建不同的产品对象，客户端应使用不同的具体工厂。

最大的好处便是易于交换产品系列，由于具体工厂类

在一个应用中只需要在初始化的时候出现一次，这就使得改变一个应用的具体工厂变得非常容易，它只需要改变具体工厂即可使用不同的产品配置。

我们的设计不能去防止需求的更改，那么我们的理想便是让改动变得最小

第二大好处是，它让具体的创建实例过程与客户端分离，客户端是通过它们的抽象接口操纵实例，产品的具体类名也被具体工厂的实现分离，不会出现在客户代码中。

是个模式都是会有缺点的，都有不适用的时候，要辨证地看待问题哦。

编程是门艺术，这样大批量的改动，显然是非常丑陋的做法。

客户端没有出现任何一个SQL Server或Access的字样，达到了解耦的目的。

依赖注入（Dependency Injection）

从这个角度上说，所有在用简单工厂的地方，都可以考虑用反射技术来去除switch或if，解除分支判断带来的耦合。

一个程序员如果从来没有熬夜写程序的经历，不能算是一个好程序员，因为他没有痴迷过，所以他不会有大成就。

无痴迷，不成功。

[source,{java_source_attr}]
.AbstractFactory 类
----
include::{source_dir}/abstract-factory/AbstractFactory.java[]
----



[source,{java_source_attr}]
.AbstractProductA 类
----
include::{source_dir}/abstract-factory/AbstractProductA.java[]
----



[source,{java_source_attr}]
.AbstractProductB 类
----
include::{source_dir}/abstract-factory/AbstractProductB.java[]
----



[source,{java_source_attr}]
.Client 类
----
include::{source_dir}/abstract-factory/Client.java[]
----



[source,{java_source_attr}]
.ConcreteFactory1 类
----
include::{source_dir}/abstract-factory/ConcreteFactory1.java[]
----



[source,{java_source_attr}]
.ConcreteFactory2 类
----
include::{source_dir}/abstract-factory/ConcreteFactory2.java[]
----



[source,{java_source_attr}]
.ProductA1 类
----
include::{source_dir}/abstract-factory/ProductA1.java[]
----



[source,{java_source_attr}]
.ProductA2 类
----
include::{source_dir}/abstract-factory/ProductA2.java[]
----



[source,{java_source_attr}]
.ProductB1 类
----
include::{source_dir}/abstract-factory/ProductB1.java[]
----



[source,{java_source_attr}]
.ProductB2 类
----
include::{source_dir}/abstract-factory/ProductB2.java[]
----


