[[command]]
== 命令模式

plantuml::./puml/command.puml[target={puml_target_dir}/command,{puml_attr}]

这其实就是‘行为请求者’与‘行为实现者’的紧耦合。

对请求排队或记录请求日志，以及支持可撤销的操作等行为时，‘行为请求者’与‘行为实现者’的紧耦合是不太适合的。

Command类，用来声明执行操作的接口。

ConcreteCommand类，将一个接收者对象绑定于一个动作，调用接收者相应的操作，以实现Execute。

Invoker类，要求该命令执行这个请求。

Receiver类，知道如何实施与执行一个与请求相关的操作，任何类都可能作为一个接收者。

客户端代码，创建一个具体命令对象并设定它的接收者。

命令模式的优点。

第一，它能较容易地设计一个命令队列；第二，在需要的情况下，可以较容易地将命令记入日志；第三，允许接收请求的一方决定是否要否决请求。

第四，可以容易地实现对请求的撤销和重做；第五，由于加进新的具体命令类不影响其他的类，因此增加新的具体命令类很容易。其实还有最关键的优点就是命令模式把请求一个操作的对象与知道怎么执行一个操作的对象分割开。[DP]

比如命令模式支持撤销/恢复操作功能，但你还不清楚是否需要这个功能时，你要不要实现命令模式？

敏捷开发原则告诉我们，不要为代码添加基于猜测的、实际不需要的功能。如果不清楚一个系统是否需要命令模式，一般就不要着急去实现它，事实上，在需要的时候通过重构实现这个模式并不困难，只有在真正需要如撤销/恢复操作等功能时，把原来的代码重构为命令模式才有意义。[R2P]

[source,{java_source_attr}]
.command/Client.java 类
[[src-command-client]]
----
include::{source_dir}/command/Client.java[]
----



[source,{java_source_attr}]
.command/Command.java 类
[[src-command-command]]
----
include::{source_dir}/command/Command.java[]
----



[source,{java_source_attr}]
.command/ConcreteCommand.java 类
[[src-command-concretecommand]]
----
include::{source_dir}/command/ConcreteCommand.java[]
----



[source,{java_source_attr}]
.command/Invoker.java 类
[[src-command-invoker]]
----
include::{source_dir}/command/Invoker.java[]
----



[source,{java_source_attr}]
.command/Receiver.java 类
[[src-command-receiver]]
----
include::{source_dir}/command/Receiver.java[]
----


