[[mediator]]
== 中介者模式

plantuml::./puml/mediator.puml[target={puml_target_dir}/mediator,{puml_attr}]

中介者模式又叫做调停者模式。其实就是中间人或者调停者的意思。

尽管将一个系统分割成许多对象通常可以增加其可复用性，但是对象间相互连接的激增又会降低其可复用性了。

大量的连接使得一个对象不可能在没有其他对象的支持下工作，系统表现为一个不可分割的整体，所以，对系统的行为进行任何较大的改动就十分困难了。

‘迪米特法则’，如果两个类不必彼此直接通信，那么这两个类就不应当发生直接的相互作用。如果其中一个类需要调用另一个类的某一个方法的话，可以通过第三者转发这个调用。

通过中介者对象，可以将系统的网状结构变成以中介者为中心的星形结构，每个具体对象不再通过直接的联系与另一个对象发生相互作用，而是通过‘中介者’对象与另一个对象发生相互作用。中介者对象的设计，使得系统的结构不会因为新对象的引入造成大量的修改工作。

Colleague叫做抽象同事类，而ConcreteColleague是具体同事类，每个具体同事只知道自己的行为，而不了解其他同事类的情况，但它们却都认识中介者对象，Mediator是抽象中介者，定义了同事对象到中介者对象的接口，ConcreteMediator是具体中介者对象，实现抽象类的方法，它需要知道所有具体同事类，并从具体同事接收消息，向具体同事对象发出命令。

Mediator类抽象中介者类

Colleague类抽象同事类

ConcreteMediator类具体中介者类

由于有了Mediator，使得ConcreteColleague1和ConcreteColleague2在发送消息和接收信息时其实是通过中介者来完成的，这就减少了它们之间的耦合度了。

中介者模式很容易在系统中应用，也很容易在系统中误用。当系统出现了‘多对多’交互复杂的对象群时，不要急于使用中介者模式，而要先反思你的系统在设计上是不是合理。

中介者模式的优点首先是Mediator的出现减少了各个Colleague的耦合，使得可以独立地改变和复用各个Colleague类和Mediator，

其次，由于把对象如何协作进行了抽象，将中介作为一个独立的概念并将其封装在一个对象中，这样关注的对象就从对象各自本身的行为转移到它们之间的交互上来，也就是站在一个更宏观的角度去看待系统。

由于ConcreteMediator控制了集中化，于是就把交互复杂性变为了中介者的复杂性，这就使得中介者会变得比任何一个ConcreteColleague都复杂。

中介者模式的优点来自集中控制，其缺点也是它，使用时是要考虑清楚哦。

中介者模式一般应用于一组对象以定义良好但是复杂的方式进行通信的场合，比如刚才得到的窗体Form对象或Web页面aspx，以及想定制一个分布在多个类中的行为，而又不想生成太多的子类的场合。

[source,{java_source_attr}]
.mediator/Colleague.java 类
[[src-mediator-colleague]]
----
include::{source_dir}/mediator/Colleague.java[]
----



[source,{java_source_attr}]
.mediator/ConcreteColleague1.java 类
[[src-mediator-concretecolleague1]]
----
include::{source_dir}/mediator/ConcreteColleague1.java[]
----



[source,{java_source_attr}]
.mediator/ConcreteColleague2.java 类
[[src-mediator-concretecolleague2]]
----
include::{source_dir}/mediator/ConcreteColleague2.java[]
----



[source,{java_source_attr}]
.mediator/ConcreteMediator.java 类
[[src-mediator-concretemediator]]
----
include::{source_dir}/mediator/ConcreteMediator.java[]
----



[source,{java_source_attr}]
.mediator/Mediator.java 类
[[src-mediator-mediator]]
----
include::{source_dir}/mediator/Mediator.java[]
----



[source,{java_source_attr}]
.mediator/Client.java 类
[[src-mediator-client]]
----
include::{source_dir}/mediator/Client.java[]
----
