[[proxy]]
== 代理模式

=== 定义

[quote,{bkn_dp}]
____
代理模式（Proxy）::
为其他对象提供一种代理以控制这个对象的访问。
____

=== 类图

plantuml::./puml/proxy.puml[target={puml_target_dir}/proxy,{puml_attr}]

Subject类，定义了RealSubject和Proxy的共用接口，这样就在任何使用RealSubject的地方都可以使用Proxy。

[source,{java_source_attr}]
.Subject 类
----
include::{source_dir}/proxy/Subject.java[]
----

RealSubject类，定义Proxy所代表的真实实体。

[source,{java_source_attr}]
.RealSubject 类
----
include::{source_dir}/proxy/RealSubject.java[]
----

Proxy类，保存一个引用使得代理可以访问实体，并提供一个与Subject的接口相同的接口，这样代理就可以用来替代实体。

[source,{java_source_attr}]
.Proxy 类
----
include::{source_dir}/proxy/Proxy.java[]
----

[source,{java_source_attr}]
.Client 类
----
include::{source_dir}/proxy/Client.java[]
----

=== 作用

一般来说分为几种，第一，远程代理，也就是为一个对象在不同的地址空间提供局部代表。这样可以隐藏一个对象存在于不同地址空间的事实[DP]。

第二种应用是虚拟代理，是根据需要创建开销很大的对象。通过它来存放实例化需要很长时间的真实对象[DP]。

第三种应用是安全代理，用来控制真实对象访问时的权限[DP]。

第四种是智能指引，是指当调用真实的对象时，代理处理另外一些事[DP]。

代理模式其实就是在访问对象时引入一定程度的间接性，因为这种间接性，可以附加多种用途。

代理就是真实对象的代表。


[WARNING]
====
在使用 ASM 生成代理 class 文件时，发现确定类文件的路径是个大问题。这里需要注意的是针对 file 的 URL 格式规范。

* https://en.wikipedia.org/wiki/File_URI_scheme[file URI scheme]
* http://stackoverflow.com/questions/13869526/is-a-file-path-a-url[Is a “file://” path a URL?]
* http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml[Uniform Resource Identifier (URI) Schemes]
* http://www.rfc-editor.org/rfc/rfc1738.txt[RFC1738: Uniform Resource Locators (URL)]
====



[source,{java_source_attr}]
.proxy/DynamicProxyMain.java 类
----
include::{source_dir}/proxy/DynamicProxyMain.java[]
----

[source,{java_source_attr}]
.proxy/PerformanceInvocationHandler.java 类
----
include::{source_dir}/proxy/PerformanceInvocationHandler.java[]
----

[source,{java_source_attr}]
.proxy/ProxyMain.java 类
----
include::{source_dir}/proxy/ProxyMain.java[]
----

[source,{java_source_attr}]
.proxy/UserService.java 类
----
include::{source_dir}/proxy/UserService.java[]
----

[source,{java_source_attr}]
.proxy/UserServiceImpl.java 类
----
include::{source_dir}/proxy/UserServiceImpl.java[]
----

[source,{java_source_attr}]
.proxy/UserServiceProxy.java 类
----
include::{source_dir}/proxy/UserServiceProxy.java[]
----

[source,{java_source_attr}]
.proxy/agent/PreMainAddTimeStatAgent.java 类
----
include::{source_dir}/proxy/agent/PreMainAddTimeStatAgent.java[]
----

[source,{java_source_attr}]
.proxy/agent/RunAccountMain.java 类
----
include::{source_dir}/proxy/agent/RunAccountMain.java[]
----

[source,{java_source_attr}]
.proxy/asm/Account.java 类
----
include::{source_dir}/proxy/asm/Account.java[]
----

[source,{java_source_attr}]
.proxy/asm/RunTimeMainAfterGen.java 类
----
include::{source_dir}/proxy/asm/RunTimeMainAfterGen.java[]
----

[source,{java_source_attr}]
.proxy/asm/TimeStat.java 类
----
include::{source_dir}/proxy/asm/TimeStat.java[]
----

[source,{java_source_attr}]
.proxy/asm/TimeStatClassAdapter.java 类
----
include::{source_dir}/proxy/asm/TimeStatClassAdapter.java[]
----

[source,{java_source_attr}]
.proxy/asm/TimeStatMethodAdapter.java 类
----
include::{source_dir}/proxy/asm/TimeStatMethodAdapter.java[]
----

[source,{java_source_attr}]
.proxy/asm/TimeStatWeaveGenerator.java 类
----
include::{source_dir}/proxy/asm/TimeStatWeaveGenerator.java[]
----
