[[singleton]]
== 单例模式


如果你不对构造方法做改动的话，是不可能阻止他人不去用new的。所以我们完全可以直接就把这个类的构造方法改成私有（private），你应该知道，所有类都有构造方法，不编码则系统默认生成空的构造方法，若有显示定义的构造方法，默认的构造方法就会失效。

客户端不再考虑是否需要去实例化的问题，而把责任都给了应该负责的类去处理。其实这就是一个很基本的设计模式：单例模式。

通常我们可以让一个全局变量使得一个对象被访问，但它不能防止你实例化多个对象。一个最好的办法就是，让类自身负责保存它的唯一实例。这个类可以保证没有其他实例可以被创建，并且它可以提供一个访问该实例的方法。[DP]

Singleton类，定义一个GetInstance操作，允许客户访问它的唯一实例。GetInstance是一个静态方法，主要负责创建自己的唯一实例。

单例模式除了可以保证唯一的实例

单例模式因为Singleton类封装它的唯一实例，这样它可以严格地控制客户怎样访问它以及何时访问它。简单地说就是对唯一实例的受控访问。

实用类通常也会采用私有化的构造方法来避免其有实例。

实用类不保存状态，仅提供一些静态方法或静态属性让你使用，而单例类是有状态的。实用类不能用于继承多态，而单例虽然实例唯一，却是可以有子类来继承。实用类只不过是一些方法属性的集合，而单例却是有着唯一的对象实例。

lock是确保当一个线程位于代码的临界区时，另一个线程不进入临界区。如果其他线程试图进入锁定的代码，则它将一直等待（即被阻止），直到该对象被释放。[MSDN]

这段代码使得对象实例由最先进入的那个线程创建，以后的线程在进入时不会再去创建对象实例了。由于有了lock，就保证了多线程环境下的同时访问也不会造成多个实例的生成。

不用让线程每次都加锁，而只是在实例未被创建的时候再加锁处理。同时也能保证多线程的安全。这种做法被称为Double-Check Locking（双重锁定）。

C#与公共语言运行库也提供了一种‘静态初始化’方法，这种方法不需要开发人员显式地编写线程安全代码，即可解决多线程环境下它是不安全的问题。[MSDN]

这样的实现与前面的示例类似，也是解决了单例模式试图解决的两个基本问题：全局访问和实例化控制，公共静态属性为访问实例提供了一个全局访问点。不同之处在于它依赖公共语言运行库来初始化变量。由于构造方法是私有的，因此不能在类本身以外实例化Singleton类；因此，变量引用的是可以在系统中存在的唯一的实例。不过要注意，instance变量标记为readonly，这意味着只能在静态初始化期间或在类构造函数中分配变量[MSDN]。由于这种静态初始化的方式是在自己被加载时就将自己实例化，所以被形象地称之为饿汉式单例类，原先的单例模式处理方式是要在第一次被引用时，才会将自己实例化，所以就被称为懒汉式单例类。[J&DP]

饿汉式，即静态初始化的方式，它是类一加载就实例化的对象，所以要提前占用系统资源。然而懒汉式，又会面临着多线程访问的安全性问题，需要做双重锁定这样的处理才可以保证安全。所以到底使用哪一种方式，取决于实际的需求。


=== 使用反射和反序列化产生多个“单例类”实例

D瓜哥根据以前学习设计模式的经验来看，单例模式的实现类只能产生一个对象。估计这也是我们大家普遍看法。但是，在一次面试时，被面试官问到“单例模式的实现类能否产生多个对象？”然后，D瓜哥当场就Hold不住了。

不过，当时善意的面试官提醒，可以用反射。昨天看《Java 程序性能优化》时，提到用反序列化也可以产生多个方法。然后，又被我同学问到这个问题。干脆写一篇文章，总结一下吧。

=== 定义

根据 GoF 的著名著作 http://book.douban.com/subject/1052241/[《设计模式》]，单例模式的定义如下：

[quote,Erich Gamma、Richard Helm、Ralph Johnson、John Vlissides,《设计模式》]
____
单例模式（Singleton）::
保证一个类仅有一个实例，并提供一个访问它的全局访问点。
____

plantuml::./puml/singleton.puml[target={puml_target_dir}/singleton,{puml_attr}]

在Java中，单例模式实现方式有两种：

* 静态初始化的方式是在自己被加载时就将自己实例化。这种方式被称为“饿汉式单例类”；
* 在第一次被引用时，才会将自己实例化。这种方式被称为“懒汉式单例类”。

下面做针对介绍。

=== 饿汉式单例类

饿汉式单例类的实现代码如下：

[source,{java_source_attr}]
.饿汉式单例类
----
include::{source_dir}/singleton/HungrySingleton.java[]
----

=== 懒汉式单例类

懒汉式单例类的实现代码如下：

[source,{java_source_attr}]
.懒汉式单例类
----
include::{source_dir}/singleton/LazySingleton.java[]
----

[source,{java_source_attr}]
.懒汉式单例类的并发测试
----
include::{source_dir}/singleton/ConcurrentTest.java[]
----

[source,{java_source_attr}]
.带 `volatile` 修饰的懒汉式单例类
----
include::{source_dir}/singleton/VolatileLazySingleton.java[]
----

[source,{java_source_attr}]
.可序列化懒汉式单例类
----
include::{source_dir}/singleton/SerializableLazySingleton.java[]
----

[source,{java_source_attr}]
.正确的可序列化懒汉式单例类
----
include::{source_dir}/singleton/CorrectSerializableLazySingleton.java[]
----

[source,{java_source_attr}]
.序列化测试
----
include::{source_dir}/singleton/SerializationTest.java[]
----

[source,{java_source_attr}]
.枚举实现的单例模式
----
include::{source_dir}/singleton/Singleton.java[]
----

[source,{java_source_attr}]
.单例模式的反射测试
----
include::{source_dir}/singleton/ReflectionTest.java[]
----

[source,{java_source_attr}]
.单例模式的 Java 黑魔法测试
----
include::{source_dir}/singleton/UnsafeTest.java[]
----

两种方式各有优缺。饿汉式，即静态初始化的方式，它是类一加载就实例化对象。所以，加载时间比较长，而且要提前占用系统资源，如果后续用不到这个对象，会造成浪费。懒汉式，又会面临多线程访问的安全性问题，需要使用双重锁定才能保证安全性，由于 Java 虚拟机的问题，在 JDK5 以后双重锁定能可以正常工作；另外，由于是在使用时初始化，在第一次调用时耗时比较长。所以，至于到底使用哪种方式，取决于实际需求。

[source,{java_source_attr}]
.并发性测试
----
include::{source_dir}/singleton/ConcurrentTest.java[]
----

=== 产生多个“单例类”实例

还回到文章开头，D瓜哥被问到的问题：单例模式的实现类能否产生多个对象？既然写这篇文章，那么答案肯定是肯定的。那么怎么产生呢？

有两种方式可以做到。我们这里分别来试验一下。


问题：既然 `static` 变量是类共享的，修改后，其他对象也应该立即修改，那么还需要 `volidate` 吗？

=== 枚举

.{java_lang_spec}
[quote,"James Gosling, Bill Joy, Guy Steele, Gilad Bracha, Alex Buckley", "{java_lang_spec} -- 8.9. Enum Types"]
____
*An enum type has no instances other than those defined by its enum constants. It is a compile-time error to attempt to explicitly instantiate an enum type (§15.9.1).*

In addition to the compile-time error, three further mechanisms ensure that no instances of an enum type exist beyond those defined by its enum constants:

* The final clone method in Enum ensures that enum constants can never be cloned.
* Reflective instantiation of enum types is prohibited.
* Special treatment by the serialization mechanism ensures that duplicate instances are never created as a result of deserialization.
____

WARNING: 不知道为啥引用的标题不能正常渲染实体？


=== 参考资料：

* http://blog.csdn.net/card361401376/article/details/51340822?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io[设计模式-单例模式(Singleton)各种写法和分析比较 - 李可乐的专栏 - 博客频道 - CSDN.NET]
* http://book.douban.com/subject/2334288/[《大话设计模式》]
* http://book.douban.com/subject/19969386/[《Java程序性能优化》]
* http://docs.oracle.com/javase/tutorial/reflect/member/ctorInstance.html[Creating New Class Instances]
* http://www.hollischuang.com/archives/1144[单例与序列化的那些事儿-HollisChuang's Blog]
* http://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.9[Chapter 8. Classes]
