[[singleton]]
== 单例模式

=== 使用反射和反序列化产生多个“单例类”实例

D瓜哥根据以前学习设计模式的经验来看，单例模式的实现类只能产生一个对象。估计这也是我们大家普遍看法。但是，在一次面试时，被面试官问到“单例模式的实现类能否产生多个对象？”然后，D瓜哥当场就Hold不住了。

不过，当时善意的面试官提醒，可以用反射。昨天看《Java程序性能优化》时，提到用反序列化也可以产生多个方法。然后，又被我同学问到这个问题。干脆写一篇文章，总结一下吧。

=== 定义

根据GoF的著名著作 http://book.douban.com/subject/1052241/[《设计模式》]，单例模式的定义如下：

[quote,Erich Gamma、Richard Helm、Ralph Johnson、John Vlissides,《设计模式》]
____
单例模式（Singleton）::
保证一个类仅有一个实例，并提供一个访问它的全局访问点。
____


在Java中，单例模式实现方式有两种：

* 静态初始化的方式是在自己被加载时就将自己实例化。这种方式被称为“饿汉式单例类”；
* 在第一次被引用时，才会将自己实例化。这种方式被称为“懒汉式单例类”。

下面做针对介绍。

=== 饿汉式单例类

饿汉式单例类的实现代码如下：

[source,java]
.饿汉式单例类
----
include::{source_dir}/singleton/HungrySingleton.java[]
----

=== 懒汉式单例类

懒汉式单例类的实现代码如下：

[source,java]
.懒汉式单例类
----
include::{source_dir}/singleton/LazySingleton.java[]
----

[source,java]
.懒汉式单例类的并发测试
----
include::{source_dir}/singleton/ConcurrentTest.java[]
----

[source,java]
.带 `volatile` 修饰的懒汉式单例类
----
include::{source_dir}/singleton/VolatileLazySingleton.java[]
----

[source,java]
.可序列化懒汉式单例类
----
include::{source_dir}/singleton/SerializableLazySingleton.java[]
----

[source,java]
.正确的可序列化懒汉式单例类
----
include::{source_dir}/singleton/CorrectSerializableLazySingleton.java[]
----

[source,java]
.序列化测试
----
include::{source_dir}/singleton/SerializationTest.java[]
----

[source,java]
.枚举实现的单例模式
----
include::{source_dir}/singleton/Singleton.java[]
----

[source,java]
.单例模式的反射测试
----
include::{source_dir}/singleton/ReflectionTest.java[]
----

[source,java]
.单例模式的 Java 黑魔法测试
----
include::{source_dir}/singleton/UnsafeTest.java[]
----

两种方式各有优缺。饿汉式，即静态初始化的方式，它是类一加载就实例化对象。所以，加载时间比较长，而且要提前占用系统资源，如果后续用不到这个对象，会造成浪费。懒汉式，又会面临多线程访问的安全性问题，需要使用双重锁定才能保证安全性，由于Java虚拟机的问题，在JDK5以后双重锁定能可以正常工作；另外，由于是在使用时初始化，在第一次调用时耗时比较长。所以，至于到底使用哪种方式，取决于实际需求。

[source,java]
.并发性测试
----
include::{source_dir}/singleton/ConcurrentTest.java[]
----

=== 产生多个“单例类”实例

还回到文章开头，D瓜哥被问到的问题：单例模式的实现类能否产生多个对象？既然写这篇文章，那么答案肯定是肯定的。那么怎么产生呢？

有两种方式可以做到。我们这里分别来试验一下。


问题：既然 `static` 变量是类共享的，修改后，其他对象也应该立即修改，那么还需要`volidate`吗？

=== 枚举

.The Java(R) Language Specification
[quote,James Gosling、Bill Joy、Guy Steele、Gilad Bracha、Alex Buckley,《The Java(R) Language Specification Java SE 8 Edition》- 8.9. Enum Types]
____
*An enum type has no instances other than those defined by its enum constants. It is a compile-time error to attempt to explicitly instantiate an enum type (§15.9.1).*

In addition to the compile-time error, three further mechanisms ensure that no instances of an enum type exist beyond those defined by its enum constants:

* The final clone method in Enum ensures that enum constants can never be cloned.
* Reflective instantiation of enum types is prohibited.
* Special treatment by the serialization mechanism ensures that duplicate instances are never created as a result of deserialization.
____

WARNING: 不知道为啥引用的标题不能正常渲染实体？


=== 参考资料：

* http://blog.csdn.net/card361401376/article/details/51340822?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io[设计模式-单例模式(Singleton)各种写法和分析比较 - 李可乐的专栏 - 博客频道 - CSDN.NET]
* http://book.douban.com/subject/2334288/[《大话设计模式》]
* http://book.douban.com/subject/19969386/[《Java程序性能优化》]
* http://docs.oracle.com/javase/tutorial/reflect/member/ctorInstance.html[Creating New Class Instances]
* http://www.hollischuang.com/archives/1144[单例与序列化的那些事儿-HollisChuang's Blog]
* http://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.9[Chapter 8. Classes]
